# Generated by Django 5.2.13 on 2026-05-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('vehicle', 'Vehicle Insurance'), ('home', 'Home Insurance'), ('travel', 'Travel Insurance')], max_length=20)),
                ('requested_cover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_requests', to='insurance.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
