# Generated by Django 5.2.13 on 2026-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_policyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrequest',
            name='payment_plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 months)'), ('halfyearly', 'Half Yearly (Every 6 months)'), ('yearly', 'Yearly (Once a year)')], default='monthly', max_length=20),
        ),
    ]
